---
{{ if and (index .Values "openshift-gitops") (index .Values "openshift-gitops" "channel") }}
{{ if (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-operators" "openshift-gitops-operator")}}
{{else}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: {{index .Values "openshift-gitops" "channel"}}
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: openshift-gitops,{{ .Release.Namespace }}
{{end}}
{{end}}
