---
{{ if and (index .Values "openshift-pipelines") (index .Values "openshift-pipelines" "channel") }}
{{ if (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-operators" "openshift-pipelines-operator")}}
{{else}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: {{index .Values "openshift-pipelines" "channel"}}
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{end}}
{{end}}
