apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}-configure"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-configure"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        {{ include "dance.acs.configure" . | indent 8 }}
        {{ include "dance.developer-hub.configure" . | indent 8 }}
        {{ include "dance.gitops.configure" . | indent 8 }}
        {{ include "dance.pipelines.configure" . | indent 8 }}
      restartPolicy: Never
      serviceAccountName: helm-manager